# This is a GitHub Actions workflow file for deploying a Django application to an Ubuntu server using Ansible.
name: Deploy Django Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook deploy.yml -i inventory
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
